### ISSUE TITLE
揚羽線文本與語音對不上

### ISSUE THREAD

**Issue by YanjenChen** [jszhtian/oozora_CHSpatch#2]
在這個選項之後，文本顯示會提早語音一句：
![image](https://user-images.githubusercontent.com/26268932/39648532-1420b904-5015-11e8-9f16-a3e91a058760.png)

問題處如下圖：
![image](https://user-images.githubusercontent.com/26268932/39648442-cc92a94e-5014-11e8-8a73-d84a1cf2dbfe.png)

推測是腳本中缺少一句或少一個人名造成的

**Comment by jszhtian** [comment]
试下最新的pre release版本

**Comment by jszhtian** [comment]
beta2中已修复
