### ISSUE TITLE
双子线sweet love文本语音对不上

### ISSUE THREAD

**Issue by KasugaYuno** [jszhtian/oozora_CHSpatch#3]
![qq 20180508223444](https://user-images.githubusercontent.com/39093223/39763756-8d4e8b00-5310-11e8-8b6a-e4ea15c48592.png)
![qq 20180508223501](https://user-images.githubusercontent.com/39093223/39763757-8d9fcf10-5310-11e8-9ea5-18a14eb9e711.png)
报错：sweet love双子线开始不久语音和对话错乱一直到结束。

具体位置：亚纱开始这句

**Comment by jszhtian** [comment]
使用prerelease 版本

**Comment by jszhtian** [comment]
![image](https://user-images.githubusercontent.com/23244094/39765746-df52854c-52e2-11e8-8e6f-4e22b15ace74.png)

**Comment by jszhtian** [comment]
由于并未最终最终完成修改工作，现在仅提供beta版本补丁
