### ISSUE TITLE
字体不能正常使用的问题。

### ISSUE THREAD

**Issue by Sum59** [jszhtian/oozora_CHSpatch#4]
程序员dalao你好，我在换字体的过程中发现一个不能正常使用字体的问题。

运行环境分别是win10的1703和1709版本，以下是出现的情况：
直接打汉化补丁使用自带的花园明朝，游戏中是中易宋体。
游戏正常关闭后，HanaMinA.ttf一直被系统占用。
把HanaMinA.ttf换成重命名后的黑体，游戏中依然是中易宋体。
把HanaMinA.ttf删除后会报错，但补丁依然能正常运行，游戏中是中易宋体。

使用调用微软雅黑的旧版补丁没有这个问题。

**Comment by jszhtian** [comment]
![image](https://user-images.githubusercontent.com/23244094/41803682-d45281ca-768b-11e8-9fa1-5bdd98ab63eb.png)
Hook前LogFont
![image](https://user-images.githubusercontent.com/23244094/41803712-20f7c59e-768c-11e8-9ad1-93d9a7b9fcae.png)
Hook中LogFont已经被替换
游戏使用CreateFontIndirectW创建字体，字体会被全部替换成HanaMinA。（newCreateFontIndirectW过程）
程序设计AddFontResourceW执行后如果加载失败，仅报错提示，并不会终止游戏。AddFontResourceW仅仅是把ttf加载进入字体列表，但创建依然由CreateFont完成。CreateFont过程中如果字体不存在，Windows会自动选择默认字体来保证正常显示。
不太清楚是不是明朝字体与宋体在加粗情况下比较类似。
换成比较明显的字体比如幼圆后可以明显看出游戏内字体变化
幼圆
![image](https://user-images.githubusercontent.com/23244094/41803880-3ace8adc-768e-11e8-935f-15e4d87fb2fe.png)
补丁默认字体
![image](https://user-images.githubusercontent.com/23244094/41803886-571aa5e0-768e-11e8-9ab1-38bce1f539a1.png)

**Comment by jszhtian** [comment]
而且目前坑主也并不想继续在这个游戏上花费时间。除非有重大bug。短时间内没有补丁更新计划。

**Comment by jszhtian** [comment]
倒是发现了一个神奇的问题。
win10下哪怕文件不存在，AddFontResource的返回值也不是0.win8上并没有这个现象。

**Comment by Sum59** [comment]
非常理解汉化组的决定。
