### ISSUE TITLE
WIN 10无法打开...

### ISSUE THREAD

**Issue by syfjhz22** [jszhtian/oozora_CHSpatch#5]
Dump Summary
------------
Dump File:	AdvHD_CHS.1D4080DBFA7BBAB.crash.dmp : E:\Galgame\WILLPLUS\この大空に、翼をひろげて\AdvHD_CHS.1D4080DBFA7BBAB.crash.dmp
Last Write Time:	2018/6/20 4:40:29
Process Name:	AdvHD_CHS.exe : E:\Galgame\WILLPLUS\この大空に、翼をひろげて\AdvHD_CHS.exe
Process Architecture:	x86
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	10.0.17134
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
AdvHD_CHS.exe	E:\Galgame\WILLPLUS\この大空に、翼をひろげて\AdvHD_CHS.exe	1.0.2.1
ntdll.dll	C:\Windows\System32\ntdll.dll	6.2.17134.112
LocaleEmulator.dll	D:\Locale.Emulator\LocaleEmulator.dll	0.0.0.0
kernel32.dll	C:\Windows\System32\kernel32.dll	6.2.17134.1
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.2.17134.112
apphelp.dll	C:\Windows\System32\apphelp.dll	6.2.17134.1
imm32.dll	C:\Windows\System32\imm32.dll	6.2.17134.1
user32.dll	C:\Windows\System32\user32.dll	6.2.17134.1
win32u.dll	C:\Windows\System32\win32u.dll	6.2.17134.1
comctl32.dll	C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17134.112_none_42ecccf244e44518\comctl32.dll	6.10.17134.112
gdi32.dll	C:\Windows\System32\gdi32.dll	6.2.17134.1
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.17134.1
gdi32full.dll	C:\Windows\System32\gdi32full.dll	6.2.17134.112
winmm.dll	C:\Windows\System32\winmm.dll	6.2.17134.1
combase.dll	C:\Windows\System32\combase.dll	6.2.17134.112
msvcp_win.dll	C:\Windows\System32\msvcp_win.dll	6.2.17134.1
ucrtbase.dll	C:\Windows\System32\ucrtbase.dll	6.2.17134.1
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.2.17134.112
sspicli.dll	C:\Windows\System32\sspicli.dll	6.2.17134.1
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.2.17134.1
advapi32.dll	C:\Windows\System32\advapi32.dll	6.2.17134.1
bcryptPrimitives.dll	C:\Windows\System32\bcryptPrimitives.dll	6.2.17134.112
sechost.dll	C:\Windows\System32\sechost.dll	6.2.17134.1
WINMMBASE.dll	C:\Windows\System32\WINMMBASE.dll	6.2.17134.1
shell32.dll	C:\Windows\System32\shell32.dll	6.2.17134.81
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	6.2.17134.1
SHCore.dll	C:\Windows\System32\SHCore.dll	6.2.17134.112
windows.storage.dll	C:\Windows\System32\windows.storage.dll	6.2.17134.81
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.2.17134.1
kernel.appcore.dll	C:\Windows\System32\kernel.appcore.dll	6.2.17134.112
profapi.dll	C:\Windows\System32\profapi.dll	6.2.17134.1
powrprof.dll	C:\Windows\System32\powrprof.dll	6.2.17134.1
d3d9.dll	C:\Windows\System32\d3d9.dll	6.2.17134.81
D3DX9_43.dll	C:\Windows\System32\D3DX9_43.dll	9.29.952.3111
dsound.dll	C:\Windows\System32\dsound.dll	6.2.17134.1
fltLib.dll	C:\Windows\System32\fltLib.dll	6.2.17134.1
ole32.dll	C:\Windows\System32\ole32.dll	6.2.17134.1
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.2.17134.48
wininet.dll	C:\Windows\System32\wininet.dll	11.0.17134.112
dwmapi.dll	C:\Windows\System32\dwmapi.dll	6.2.17134.1
msvcr90.dll	C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9415_none_508df7e2bcbccb90\msvcr90.dll	9.0.30729.9415
lua5.1.dll	E:\Galgame\WILLPLUS\この大空に、翼をひろげて\lua5.1.dll	5.1.4.0
XINPUT1_3.dll	C:\Windows\System32\XINPUT1_3.dll	9.18.944.0
setupapi.dll	C:\Windows\System32\setupapi.dll	6.2.17134.1
msvcr80.dll	C:\Windows\WinSxS\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9445_none_d08c58b4442ba54f\msvcr80.dll	8.0.50727.9445
AdvPatch.dll	E:\Galgame\WILLPLUS\この大空に、翼をひろげて\AdvPatch.dll	1.0.0.2
vcomp140.dll	C:\Windows\System32\vcomp140.dll	14.10.25008.0
uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.2.17134.1
msctf.dll	C:\Windows\System32\msctf.dll	6.2.17134.1
nvldumd.dll	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f936d37e592b25aa\nvldumd.dll	23.21.13.8813
version.dll	C:\Windows\System32\version.dll	6.2.17134.1
crypt32.dll	C:\Windows\System32\crypt32.dll	6.2.17134.1
msasn1.dll	C:\Windows\System32\msasn1.dll	6.2.17134.1
wintrust.dll	C:\Windows\System32\wintrust.dll	6.2.17134.81
imagehlp.dll	C:\Windows\System32\imagehlp.dll	6.2.17134.1
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.2.17134.1
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.2.17134.1
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.2.17134.112
nvd3dum.dll	C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_f936d37e592b25aa\nvd3dum.dll	23.21.13.8813
nvspcap.dll	C:\Windows\System32\nvspcap.dll	3.10.0.95
ntmarta.dll	C:\Windows\System32\ntmarta.dll	6.2.17134.1
TextInputFramework.dll	C:\Windows\System32\TextInputFramework.dll	6.2.17134.1
CoreUIComponents.dll	C:\Windows\System32\CoreUIComponents.dll	6.2.17134.112
CoreMessaging.dll	C:\Windows\System32\CoreMessaging.dll	6.2.17134.112
WinTypes.dll	C:\Windows\System32\WinTypes.dll	6.2.17134.112
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.10941.16384
QQPinyinTSF.dll	C:\Windows\System32\IME\QQPinyinTSF\QQPinyinTSF.dll	6.0.5005.400
wtsapi32.dll	C:\Windows\System32\wtsapi32.dll	6.2.17134.1
winsta.dll	C:\Windows\System32\winsta.dll	6.2.17134.1
QQPinyin.ime	C:\Windows\System32\IME\QQPinyinTSF\QQPinyin.ime	6.0.5005.400
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.2.17134.1
psapi.dll	C:\Windows\System32\psapi.dll	6.2.17134.1
msimg32.dll	C:\Windows\System32\msimg32.dll	6.2.17134.1
coml2.dll	C:\Windows\System32\coml2.dll	6.2.17134.1
propsys.dll	C:\Windows\System32\propsys.dll	7.0.17134.112
dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.2.17134.1
edputil.dll	C:\Windows\System32\edputil.dll	6.2.17134.1
Windows.StateRepositoryPS.dll	C:\Windows\System32\Windows.StateRepositoryPS.dll	6.2.17134.112
urlmon.dll	C:\Windows\System32\urlmon.dll	11.0.17134.112
iertutil.dll	C:\Windows\System32\iertutil.dll	11.0.17134.112
cldapi.dll	C:\Windows\System32\cldapi.dll	6.2.17134.1
dbgcore.dll	C:\Windows\System32\dbgcore.dll	6.2.17134.1
ntshrui.dll	C:\Windows\System32\ntshrui.dll	6.2.17134.1
srvcli.dll	C:\Windows\System32\srvcli.dll	6.2.17134.1
cscapi.dll	C:\Windows\System32\cscapi.dll	6.2.17134.1
mssprxy.dll	C:\Windows\System32\mssprxy.dll	7.0.17134.1
linkinfo.dll	C:\Windows\System32\linkinfo.dll	6.2.17134.1

--------------

原版一切正常，汉化版无法打开，错误如上...

**Comment by syfjhz22** [comment]
我去，自查了一下竟然是和QQ拼音有冲突……
切换掉后即可运行...Orz

**Comment by jszhtian** [comment]
输入法问题曾经有人报告过，本地复现失败。
QQ拼音究竟干啥了。。。这谁知道Orz
